// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using EventPro.DAL.Models;

#nullable disable

namespace EventPro.DAL.Migrations
{
    [DbContext(typeof(EventProContext))]
    partial class EventProContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventPro.DAL.Models.CardInfo", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CardId"));

                    b.Property<string>("AddTextFontAlignment")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)");

                    b.Property<double?>("AddTextRightAxis")
                        .HasColumnType("float");

                    b.Property<string>("AltTextFontColor")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("AltTextFontName")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<double?>("AltTextFontSize")
                        .HasColumnType("float");

                    b.Property<double?>("AltTextXaxis")
                        .HasColumnType("float")
                        .HasColumnName("AltTextXAxis");

                    b.Property<double?>("AltTextYaxis")
                        .HasColumnType("float")
                        .HasColumnName("AltTextYAxis");

                    b.Property<string>("BackgroundColor")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("BackgroundImage")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<bool?>("BarcodeBorder")
                        .HasColumnType("bit");

                    b.Property<string>("BarcodeColorCode")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("BarcodeHeight")
                        .HasColumnType("int");

                    b.Property<int?>("BarcodeWidth")
                        .HasColumnType("int");

                    b.Property<double?>("BarcodeXaxis")
                        .HasColumnType("float")
                        .HasColumnName("BarcodeXAxis");

                    b.Property<double?>("BarcodeYaxis")
                        .HasColumnType("float")
                        .HasColumnName("BarcodeYAxis");

                    b.Property<int?>("CardHeight")
                        .HasColumnType("int");

                    b.Property<int?>("CardWidth")
                        .HasColumnType("int");

                    b.Property<double?>("ContactNameXaxis")
                        .HasColumnType("float")
                        .HasColumnName("ContactNameXAxis");

                    b.Property<double?>("ContactNameYaxis")
                        .HasColumnType("float")
                        .HasColumnName("ContactNameYAxis");

                    b.Property<string>("ContactNoAlignment")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("ContactNoFontColor")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("ContactNoFontName")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<double?>("ContactNoFontSize")
                        .HasColumnType("float");

                    b.Property<double?>("ContactNoXaxis")
                        .HasColumnType("float")
                        .HasColumnName("ContactNoXAxis");

                    b.Property<double?>("ContactNoYaxis")
                        .HasColumnType("float")
                        .HasColumnName("ContactNoYAxis");

                    b.Property<double?>("ContactRightAxis")
                        .HasColumnType("float");

                    b.Property<string>("DefaultFont")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<int?>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("FontAlignment")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("FontColor")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("FontName")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<double?>("FontSize")
                        .HasColumnType("float");

                    b.Property<string>("FontStyleAddText")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("FontStyleMobNo")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("FontStyleName")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("FontStyleNos")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("ForegroundColor")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<double?>("NameRightAxis")
                        .HasColumnType("float");

                    b.Property<string>("NosAlignment")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)");

                    b.Property<double?>("NosRightAxis")
                        .HasColumnType("float");

                    b.Property<string>("NosfontColor")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("NOSFontColor");

                    b.Property<string>("NosfontName")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("NOSFontName");

                    b.Property<double?>("NosfontSize")
                        .HasColumnType("float")
                        .HasColumnName("NOSFontSize");

                    b.Property<double?>("Nosxaxis")
                        .HasColumnType("float")
                        .HasColumnName("NOSXAxis");

                    b.Property<double?>("Nosyaxis")
                        .HasColumnType("float")
                        .HasColumnName("NOSYAxis");

                    b.Property<bool?>("RightAlignment")
                        .HasColumnType("bit");

                    b.Property<string>("SelectedPlaceHolder")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<bool?>("TransparentBackground")
                        .HasColumnType("bit");

                    b.HasKey("CardId")
                        .HasName("PK__CardInfo__55FECDAE4B958A2D");

                    b.HasIndex("EventId");

                    b.ToTable("CardInfo");
                });

            modelBuilder.Entity("EventPro.DAL.Models.EventCategory", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<string>("Category")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Icon")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.HasKey("EventId")
                        .HasName("PK__EventCat__7944C810DB34F5B1");

                    b.HasIndex("CreatedBy");

                    b.ToTable("EventCategory");
                });

            modelBuilder.Entity("EventPro.DAL.Models.EventGatekeeperMapping", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskId"));

                    b.Property<int?>("AssignedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AsssignedOn")
                        .HasColumnType("datetime");

                    b.Property<int?>("EventId")
                        .HasColumnType("int");

                    b.Property<int?>("GatekeeperId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.HasKey("TaskId")
                        .HasName("PK__EventGat__7C6949B1EFFB8CEC");

                    b.HasIndex("AssignedBy");

                    b.HasIndex("EventId");

                    b.HasIndex("GatekeeperId");

                    b.ToTable("EventGatekeeperMapping");
                });

            modelBuilder.Entity("EventPro.DAL.Models.EventLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Governorate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EventLocations");
                });

            modelBuilder.Entity("EventPro.DAL.Models.Events", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AttendanceTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedFor")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<int?>("EventCode")
                        .HasColumnType("int");

                    b.Property<string>("EventDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EventFrom")
                        .HasColumnType("datetime");

                    b.Property<string>("EventLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EventLocationId")
                        .HasColumnType("int");

                    b.Property<string>("EventTitle")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime?>("EventTo")
                        .HasColumnType("datetime");

                    b.Property<string>("EventVenue")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("GmapCode")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("GMapCode");

                    b.Property<bool?>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("ParentTitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ParentTitleGender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ShowOnCalender")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedFor");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("Type");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("EventPro.DAL.Models.GKEventHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CheckType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Event_Id")
                        .HasColumnType("int");

                    b.Property<int>("GK_Id")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LogDT")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("GKEventHistory");
                });

            modelBuilder.Entity("EventPro.DAL.Models.Guest", b =>
                {
                    b.Property<int>("GuestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GuestId"));

                    b.Property<string>("AdditionalText")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Address")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool?>("Archived")
                        .HasColumnType("bit");

                    b.Property<int?>("CountryCode")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Cypertext")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<int?>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("GateKeeper")
                        .HasColumnType("int");

                    b.Property<bool?>("ImgDelivered")
                        .HasColumnType("bit");

                    b.Property<bool?>("ImgFailed")
                        .HasColumnType("bit");

                    b.Property<bool?>("ImgRead")
                        .HasColumnType("bit");

                    b.Property<string>("ImgSenOn")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<bool?>("ImgSent")
                        .HasColumnType("bit");

                    b.Property<string>("ImgSentMsgId")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MessageId")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ModeOfCommunication")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MsgResponse")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int?>("NoOfMembers")
                        .HasColumnType("int");

                    b.Property<string>("PrimaryContactNo")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Qrresponse")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("QRResponse");

                    b.Property<string>("Response")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("SecondaryContactNo")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Source")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<bool?>("TextDelivered")
                        .HasColumnType("bit");

                    b.Property<bool?>("TextFailed")
                        .HasColumnType("bit");

                    b.Property<bool?>("TextRead")
                        .HasColumnType("bit");

                    b.Property<bool?>("TextSent")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("WaresponseTime")
                        .HasColumnType("datetime")
                        .HasColumnName("WAResponseTime");

                    b.Property<string>("WasentOn")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("WASentOn");

                    b.Property<string>("WhatsappStatus")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("GuestId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("EventId");

                    b.HasIndex("GateKeeper");

                    b.ToTable("Guest");
                });

            modelBuilder.Entity("EventPro.DAL.Models.InvoiceDetails", b =>
                {
                    b.Property<int>("Idid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idid"));

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<string>("NoFguest")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("NoFGuest");

                    b.Property<string>("Product")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal?>("Qty")
                        .HasColumnType("money");

                    b.Property<decimal?>("Rate")
                        .HasColumnType("money");

                    b.Property<decimal?>("Total")
                        .HasColumnType("money");

                    b.HasKey("Idid")
                        .HasName("PK__InvoiceD__B87DF1C449EDCD95");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceDetails");
                });

            modelBuilder.Entity("EventPro.DAL.Models.Invoices", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BillTo")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("BillingAddress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("BillingContactNo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("date");

                    b.Property<string>("EventCode")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("EventLocation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EventName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EventPlace")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("InvoiceDate")
                        .HasColumnType("date");

                    b.Property<bool?>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<decimal?>("NetDue")
                        .HasColumnType("money");

                    b.Property<decimal?>("TaxPer")
                        .HasColumnType("money");

                    b.Property<decimal?>("TotalDue")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.HasIndex("EventCode")
                        .IsUnique()
                        .HasDatabaseName("UQ__Invoices__640F671637A0326E")
                        .HasFilter("[EventCode] IS NOT NULL");

                    b.HasIndex("EventId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("EventPro.DAL.Models.LocallizationMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LabelName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("RegionCode")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Translation")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("LocallizationMaster");
                });

            modelBuilder.Entity("EventPro.DAL.Models.Roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("RoleName")
                        .IsUnique()
                        .HasDatabaseName("UQ__Roles__8A2B6160339910C6")
                        .HasFilter("[RoleName] IS NOT NULL");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("EventPro.DAL.Models.ScanHistory", b =>
                {
                    b.Property<int>("ScanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScanId"));

                    b.Property<int?>("GuestId")
                        .HasColumnType("int");

                    b.Property<string>("Response")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ResponseCode")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("ScanBy")
                        .HasColumnType("int");

                    b.Property<string>("ScannedCode")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("ScannedOn")
                        .HasColumnType("datetime");

                    b.HasKey("ScanId")
                        .HasName("PK__ScanHist__63B326812054FE6F");

                    b.HasIndex("GuestId");

                    b.HasIndex("ScanBy");

                    b.ToTable("ScanHistory");
                });

            modelBuilder.Entity("EventPro.DAL.Models.SerilogScan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SeriLog");
                });

            modelBuilder.Entity("EventPro.DAL.Models.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("BankAccountNo")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("BankName")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Gender")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Ibnnumber")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("IBNNumber");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("LockedOn")
                        .HasColumnType("datetime");

                    b.Property<int?>("LoginAttempt")
                        .HasColumnType("int");

                    b.Property<string>("ModeOfCommunication")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Password")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PreferedTimeZone")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PrimaryContactNo")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<int?>("Role")
                        .HasColumnType("int");

                    b.Property<string>("SecondaryContantNo")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("TemporaryPass")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("UserName")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CC4CDDBA614D");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("Role");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("UQ__Users__C9F2845664DD6561")
                        .HasFilter("[UserName] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EventPro.DAL.Models.ValidateQRCodeResult", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("No")
                        .HasColumnType("int");

                    b.Property<int>("Scanned")
                        .HasColumnType("int");

                    b.Property<string>("message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("succeed")
                        .HasColumnType("bit");

                    b.ToTable("ValidateQRCodeResult");
                });

            modelBuilder.Entity("EventPro.DAL.Models.VwEventCategory", b =>
                {
                    b.Property<string>("Category")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Icon")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("LastName")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.ToTable((string)null);

                    b.ToView("Vw_EventCategory", (string)null);
                });

            modelBuilder.Entity("EventPro.DAL.Models.VwEventGatekeeper", b =>
                {
                    b.Property<string>("Address")
                        .HasMaxLength(400)
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.Property<string>("BankAccountNo")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("BankName")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<int?>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("FullName")
                        .HasMaxLength(81)
                        .IsUnicode(false)
                        .HasColumnType("varchar(81)");

                    b.Property<string>("Gender")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Ibnnumber")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("IBNNumber");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<DateTime?>("LockedOn")
                        .HasColumnType("datetime");

                    b.Property<int?>("LoginAttempt")
                        .HasColumnType("int");

                    b.Property<string>("ModeOfCommunication")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Password")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PreferedTimeZone")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PrimaryContactNo")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<int?>("Role")
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("SecondaryContantNo")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<int?>("TaskId")
                        .HasColumnType("int");

                    b.Property<string>("TemporaryPass")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.ToTable((string)null);

                    b.ToView("vw_EventGatekeeper", (string)null);
                });

            modelBuilder.Entity("EventPro.DAL.Models.VwEvents", b =>
                {
                    b.Property<string>("Category")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedFor")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<int?>("EventCode")
                        .HasColumnType("int");

                    b.Property<string>("EventDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EventFrom")
                        .HasColumnType("datetime");

                    b.Property<string>("EventTitle")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime?>("EventTo")
                        .HasColumnType("datetime");

                    b.Property<string>("EventVenue")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Glocation")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("GLocation");

                    b.Property<string>("GmapCode")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8000)");

                    b.Property<string>("Icon")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(76)
                        .IsUnicode(false)
                        .HasColumnType("varchar(76)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool?>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("Vw_Events", (string)null);
                });

            modelBuilder.Entity("EventPro.DAL.Models.VwGateKeeperData", b =>
                {
                    b.Property<DateTime?>("EventFrom")
                        .HasColumnType("datetime");

                    b.Property<string>("EventTitle")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime?>("EventTo")
                        .HasColumnType("datetime");

                    b.Property<string>("EventVenue")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FullName")
                        .HasMaxLength(61)
                        .HasColumnType("nvarchar(61)");

                    b.Property<int?>("GatekeeperId")
                        .HasColumnType("int");

                    b.Property<string>("GmapCode")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("GMapCode");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<long?>("RowId")
                        .HasColumnType("bigint");

                    b.Property<int?>("Scanned")
                        .HasColumnType("int");

                    b.Property<int?>("TotalAllocated")
                        .HasColumnType("int");

                    b.Property<int?>("UniqueFamily")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("Vw_GateKeeperData", (string)null);
                });

            modelBuilder.Entity("EventPro.DAL.Models.VwGateKeeperScheduled", b =>
                {
                    b.Property<int?>("AssignedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AsssignedOn")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("EventFrom")
                        .HasColumnType("datetime");

                    b.Property<int?>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("EventTitle")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime?>("EventTo")
                        .HasColumnType("datetime");

                    b.Property<string>("EventVenue")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("GatekeeperId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vw_GateKeeperScheduled", (string)null);
                });

            modelBuilder.Entity("EventPro.DAL.Models.VwGuestList", b =>
                {
                    b.Property<DateTime?>("EventFrom")
                        .HasColumnType("datetime");

                    b.Property<string>("EventTitle")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime?>("EventTo")
                        .HasColumnType("datetime");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("GuestId")
                        .HasColumnType("int");

                    b.Property<string>("PrimarycontactNo")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.ToTable((string)null);

                    b.ToView("Vw_GuestList", (string)null);
                });

            modelBuilder.Entity("EventPro.DAL.Models.VwGuestReportWa", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("EventTitle")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("GuestId")
                        .HasColumnType("int");

                    b.Property<bool?>("ImgDelivered")
                        .HasColumnType("bit");

                    b.Property<bool?>("ImgFailed")
                        .HasColumnType("bit");

                    b.Property<bool?>("ImgRead")
                        .HasColumnType("bit");

                    b.Property<bool?>("ImgSent")
                        .HasColumnType("bit");

                    b.Property<string>("MessageId")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PrimaryContactNo")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Response")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<bool?>("TextDelivered")
                        .HasColumnType("bit");

                    b.Property<bool?>("TextFailed")
                        .HasColumnType("bit");

                    b.Property<bool?>("TextRead")
                        .HasColumnType("bit");

                    b.Property<bool?>("TextSent")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("WaresponseTime")
                        .HasColumnType("datetime")
                        .HasColumnName("WAResponseTime");

                    b.ToTable((string)null);

                    b.ToView("vw_GuestReportWA", (string)null);
                });

            modelBuilder.Entity("EventPro.DAL.Models.VwMiagregationReport", b =>
                {
                    b.Property<int?>("Allowed")
                        .HasColumnType("int");

                    b.Property<int?>("Declined")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("EventTitle")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("eventTitle");

                    b.Property<int?>("ImgDelivered")
                        .HasColumnType("int");

                    b.Property<int?>("ImgFailed")
                        .HasColumnType("int");

                    b.Property<int?>("ImgRead")
                        .HasColumnType("int");

                    b.Property<int?>("ImgSent")
                        .HasColumnType("int");

                    b.Property<int?>("NoResponse")
                        .HasColumnType("int");

                    b.Property<int?>("TextDelivered")
                        .HasColumnType("int");

                    b.Property<int?>("TextFailed")
                        .HasColumnType("int");

                    b.Property<int?>("TextRead")
                        .HasColumnType("int");

                    b.Property<int?>("TextSent")
                        .HasColumnType("int");

                    b.Property<int?>("TotalFamily")
                        .HasColumnType("int");

                    b.Property<int?>("TotalGuest")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("WaitingResponse")
                        .HasColumnType("int");

                    b.Property<int?>("WhatsappNotExists")
                        .HasColumnType("int");

                    b.Property<int?>("YesResponse")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vw_MIAgregationReport", (string)null);
                });

            modelBuilder.Entity("EventPro.DAL.Models.VwScanForCount", b =>
                {
                    b.Property<string>("EventDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EventFrom")
                        .HasColumnType("datetime");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("EventTitle")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("EventVenue")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("GuestId")
                        .HasColumnType("int");

                    b.Property<int?>("NoOfMembers")
                        .HasColumnType("int");

                    b.Property<string>("Response")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ResponseCode")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("ScanBy")
                        .HasColumnType("int");

                    b.Property<int>("ScanId")
                        .HasColumnType("int");

                    b.Property<string>("ScannedCode")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("ScannedOn")
                        .HasColumnType("datetime");

                    b.ToTable((string)null);

                    b.ToView("Vw_ScanForCount", (string)null);
                });

            modelBuilder.Entity("EventPro.DAL.Models.VwScanHistory", b =>
                {
                    b.Property<string>("EventDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EventFrom")
                        .HasColumnType("datetime");

                    b.Property<string>("EventTitle")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("EventVenue")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("GuestId")
                        .HasColumnType("int");

                    b.Property<int?>("NoOfMembers")
                        .HasColumnType("int");

                    b.Property<string>("Response")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ResponseCode")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("ScanBy")
                        .HasColumnType("int");

                    b.Property<int>("ScanId")
                        .HasColumnType("int");

                    b.Property<string>("ScannedCode")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("ScannedOn")
                        .HasColumnType("datetime");

                    b.ToTable((string)null);

                    b.ToView("Vw_ScanHistory", (string)null);
                });

            modelBuilder.Entity("EventPro.DAL.Models.VwScanHistoryLogs", b =>
                {
                    b.Property<string>("Category")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("CreatedFor")
                        .HasColumnType("int");

                    b.Property<string>("EventCode")
                        .HasMaxLength(8000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8000)");

                    b.Property<DateTime?>("EventFrom")
                        .HasColumnType("datetime");

                    b.Property<string>("EventTitle")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime?>("EventTo")
                        .HasColumnType("datetime");

                    b.Property<int?>("GuestId")
                        .HasColumnType("int");

                    b.Property<string>("GuestName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Icon")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<int?>("Nos")
                        .HasColumnType("int");

                    b.Property<string>("Response")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ResponseCode")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("ScanBy")
                        .HasColumnType("int");

                    b.Property<int>("ScanId")
                        .HasColumnType("int");

                    b.Property<string>("ScannedBy")
                        .HasMaxLength(81)
                        .IsUnicode(false)
                        .HasColumnType("varchar(81)");

                    b.Property<string>("ScannedCode")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("ScannedOn")
                        .HasColumnType("datetime");

                    b.ToTable((string)null);

                    b.ToView("Vw_ScanHistoryLogs", (string)null);
                });

            modelBuilder.Entity("EventPro.DAL.Models.VwScannedInfo", b =>
                {
                    b.Property<string>("AdditionalText")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Address")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Cypertext")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<int?>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("GateKeeper")
                        .HasColumnType("int");

                    b.Property<int>("GuestId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ImageTime")
                        .HasColumnType("datetime");

                    b.Property<bool?>("ImgDelivered")
                        .HasColumnType("bit");

                    b.Property<bool?>("ImgFailed")
                        .HasColumnType("bit");

                    b.Property<bool?>("ImgRead")
                        .HasColumnType("bit");

                    b.Property<bool?>("ImgSent")
                        .HasColumnType("bit");

                    b.Property<string>("ImgSentMsgId")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MessageId")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("ModeOfCommunication")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("NoOfMembers")
                        .HasColumnType("int");

                    b.Property<string>("PrimaryContactNo")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Response")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Scanned")
                        .HasColumnType("int");

                    b.Property<string>("SecondaryContactNo")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Source")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<bool?>("TextDelivered")
                        .HasColumnType("bit");

                    b.Property<bool?>("TextFailed")
                        .HasColumnType("bit");

                    b.Property<bool?>("TextRead")
                        .HasColumnType("bit");

                    b.Property<bool?>("TextSent")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("TextTime")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("WaresponseTime")
                        .HasColumnType("datetime")
                        .HasColumnName("WAResponseTime");

                    b.Property<string>("WhatsappStatus")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.ToTable((string)null);

                    b.ToView("vw_ScannedInfo", (string)null);
                });

            modelBuilder.Entity("EventPro.DAL.Models.VwUsers", b =>
                {
                    b.Property<string>("Address")
                        .HasMaxLength(400)
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.Property<string>("BankAccountNo")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("BankName")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("FullName")
                        .HasMaxLength(81)
                        .IsUnicode(false)
                        .HasColumnType("varchar(81)");

                    b.Property<string>("Gender")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Ibnnumber")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("IBNNumber");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<DateTime?>("LockedOn")
                        .HasColumnType("datetime");

                    b.Property<int?>("LoginAttempt")
                        .HasColumnType("int");

                    b.Property<string>("ModeOfCommunication")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Password")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PreferedTimeZone")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PrimaryContactNo")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<int?>("Role")
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("SecondaryContantNo")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("TemporaryPass")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.ToTable((string)null);

                    b.ToView("Vw_Users", (string)null);
                });

            modelBuilder.Entity("EventPro.DAL.Models.WhatsappResponseLogs", b =>
                {
                    b.Property<int>("WaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WaId"));

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("RecepientNo")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Response")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<long?>("Ticks")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Wakey")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("WAKey");

                    b.HasKey("WaId")
                        .HasName("PK__Whatsapp__81F5B101D6599776");

                    b.ToTable("WhatsappResponseLogs");
                });

            modelBuilder.Entity("EventPro.DAL.Models.CardInfo", b =>
                {
                    b.HasOne("EventPro.DAL.Models.Events", "Event")
                        .WithMany("CardInfo")
                        .HasForeignKey("EventId")
                        .HasConstraintName("FK__CardInfo__EventI__160F4887");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("EventPro.DAL.Models.EventCategory", b =>
                {
                    b.HasOne("EventPro.DAL.Models.Users", "CreatedByNavigation")
                        .WithMany("EventCategory")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__EventCate__Creat__412EB0B6");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("EventPro.DAL.Models.EventGatekeeperMapping", b =>
                {
                    b.HasOne("EventPro.DAL.Models.Users", "AssignedByNavigation")
                        .WithMany("EventGatekeeperMappingAssignedByNavigation")
                        .HasForeignKey("AssignedBy")
                        .HasConstraintName("FK__EventGate__Assig__51300E55");

                    b.HasOne("EventPro.DAL.Models.Events", "Event")
                        .WithMany("EventGatekeeperMapping")
                        .HasForeignKey("EventId")
                        .HasConstraintName("FK__EventGate__Event__4F47C5E3");

                    b.HasOne("EventPro.DAL.Models.Users", "Gatekeeper")
                        .WithMany("EventGatekeeperMappingGatekeeper")
                        .HasForeignKey("GatekeeperId")
                        .HasConstraintName("FK__EventGate__Gatek__503BEA1C");

                    b.Navigation("AssignedByNavigation");

                    b.Navigation("Event");

                    b.Navigation("Gatekeeper");
                });

            modelBuilder.Entity("EventPro.DAL.Models.Events", b =>
                {
                    b.HasOne("EventPro.DAL.Models.Users", "CreatedByNavigation")
                        .WithMany("EventsCreatedByNavigation")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__Events__CreatedB__44FF419A");

                    b.HasOne("EventPro.DAL.Models.Users", "CreatedForNavigation")
                        .WithMany("EventsCreatedForNavigation")
                        .HasForeignKey("CreatedFor")
                        .HasConstraintName("FK__Events__CreatedF__45F365D3");

                    b.HasOne("EventPro.DAL.Models.Users", "ModifiedByNavigation")
                        .WithMany("EventsModifiedByNavigation")
                        .HasForeignKey("ModifiedBy")
                        .HasConstraintName("FK__Events__Modified__46E78A0C");

                    b.HasOne("EventPro.DAL.Models.EventCategory", "TypeNavigation")
                        .WithMany("Events")
                        .HasForeignKey("Type")
                        .HasConstraintName("FK__Events__Type__440B1D61");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("CreatedForNavigation");

                    b.Navigation("ModifiedByNavigation");

                    b.Navigation("TypeNavigation");
                });

            modelBuilder.Entity("EventPro.DAL.Models.Guest", b =>
                {
                    b.HasOne("EventPro.DAL.Models.Users", "CreatedByNavigation")
                        .WithMany("GuestCreatedByNavigation")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__Guest__CreatedBy__2DE6D218");

                    b.HasOne("EventPro.DAL.Models.Events", "Event")
                        .WithMany("Guest")
                        .HasForeignKey("EventId")
                        .HasConstraintName("FK__Guest__EventId__2EDAF651");

                    b.HasOne("EventPro.DAL.Models.Users", "GateKeeperNavigation")
                        .WithMany("GuestGateKeeperNavigation")
                        .HasForeignKey("GateKeeper")
                        .HasConstraintName("FK__Guest__GateKeepe__2FCF1A8A");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Event");

                    b.Navigation("GateKeeperNavigation");
                });

            modelBuilder.Entity("EventPro.DAL.Models.InvoiceDetails", b =>
                {
                    b.HasOne("EventPro.DAL.Models.Invoices", "Invoice")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("InvoiceId")
                        .HasConstraintName("FK__InvoiceDe__Invoi__1F63A897");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("EventPro.DAL.Models.Invoices", b =>
                {
                    b.HasOne("EventPro.DAL.Models.Events", "Event")
                        .WithMany("Invoices")
                        .HasForeignKey("EventId")
                        .HasConstraintName("FK__Invoices__EventI__1C873BEC");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("EventPro.DAL.Models.ScanHistory", b =>
                {
                    b.HasOne("EventPro.DAL.Models.Guest", "Guest")
                        .WithMany("ScanHistory")
                        .HasForeignKey("GuestId")
                        .HasConstraintName("FK__ScanHisto__Guest__3D2915A8");

                    b.HasOne("EventPro.DAL.Models.Users", "ScanByNavigation")
                        .WithMany("ScanHistory")
                        .HasForeignKey("ScanBy")
                        .HasConstraintName("FK__ScanHisto__ScanB__3C34F16F");

                    b.Navigation("Guest");

                    b.Navigation("ScanByNavigation");
                });

            modelBuilder.Entity("EventPro.DAL.Models.Users", b =>
                {
                    b.HasOne("EventPro.DAL.Models.Users", "CreatedByNavigation")
                        .WithMany("InverseCreatedByNavigation")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__Users__CreatedBy__3A81B327");

                    b.HasOne("EventPro.DAL.Models.Users", "ModifiedByNavigation")
                        .WithMany("InverseModifiedByNavigation")
                        .HasForeignKey("ModifiedBy")
                        .HasConstraintName("FK__Users__ModifiedB__3B75D760");

                    b.HasOne("EventPro.DAL.Models.Roles", "RoleNavigation")
                        .WithMany("Users")
                        .HasForeignKey("Role")
                        .HasConstraintName("FK__Users__Role__4F7CD00D");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("ModifiedByNavigation");

                    b.Navigation("RoleNavigation");
                });

            modelBuilder.Entity("EventPro.DAL.Models.EventCategory", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("EventPro.DAL.Models.Events", b =>
                {
                    b.Navigation("CardInfo");

                    b.Navigation("EventGatekeeperMapping");

                    b.Navigation("Guest");

                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("EventPro.DAL.Models.Guest", b =>
                {
                    b.Navigation("ScanHistory");
                });

            modelBuilder.Entity("EventPro.DAL.Models.Invoices", b =>
                {
                    b.Navigation("InvoiceDetails");
                });

            modelBuilder.Entity("EventPro.DAL.Models.Roles", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("EventPro.DAL.Models.Users", b =>
                {
                    b.Navigation("EventCategory");

                    b.Navigation("EventGatekeeperMappingAssignedByNavigation");

                    b.Navigation("EventGatekeeperMappingGatekeeper");

                    b.Navigation("EventsCreatedByNavigation");

                    b.Navigation("EventsCreatedForNavigation");

                    b.Navigation("EventsModifiedByNavigation");

                    b.Navigation("GuestCreatedByNavigation");

                    b.Navigation("GuestGateKeeperNavigation");

                    b.Navigation("InverseCreatedByNavigation");

                    b.Navigation("InverseModifiedByNavigation");

                    b.Navigation("ScanHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
